### ISSUE TITLE
[Feature request] Support for folders inside git trees

### ISSUE THREAD

**Issue by jfsiii** [pablopunk/bashy#2]
The current behavior only works if the current folder _is_ a git repo. It doesn't work if the folder is _in_ a git repo.

You can test if a directory is inside a git tree with

```
git rev-parse --is-inside-work-tree &>/dev/null
```

[`git rev-parse --is-inside-work-tree`](https://git-scm.com/docs/git-rev-parse#git-rev-parse---is-inside-work-tree) will print `true` or `false`. However, it will send `fatal: Not a git repository (or any of the parent directories): .git` to STDERR, so adding `&>/dev/null` prevents either STDOUT or STDERR from printing to the screen.

**Comment by pablopunk** [comment]
Wow, I actually thought about this and never did it cause I thought it will add a lot of time to the script. It seems that it doesn't:

```shell
real    0m0.025s
user    0m0.011s
sys     0m0.008s
```

Thanks @jfsiii !
