### ISSUE TITLE
Prompt bug browsing history

### ISSUE THREAD

**Issue by pablopunk** [pablopunk/bashy#4]
When you press the UP arrow to navigate through the history,
eventually the prompt is deleted and the history overlaps the whole line.

This also happens when the current command exceeds the terminal width,
which can be solved escaping `PS1` with `export PS1="\[$(bashy)\] $ "`
but the history problem is still happening.

I had this error before, and it was because not escaping the 0 length 
characters like `$bold` in the PS1 variable. The problem now is that
in `bashy` I'm not setting the variable itself, I just use `echo` to print it,
and escaping these variables (`\[$bold\]`) doesn't work cause those
characters are just for variables and not for `echo`.

BTW, consider using `printf` instead of `echo`. It doesn't solve the problem
but is better for compatibility.

**Comment by egeriis** [comment]
How do I solve this, @pablopunk?

**Comment by pablopunk** [comment]
@egeriis I have no idea at this moment 😕

**Comment by egeriis** [comment]
@pablopunk You mention that `$bold` needs to be escaped, how is that accomplished? Do you know?

**Comment by pablopunk** [comment]
@egeriis basically it would be something like `PS1="\[$bold\]my prompt$ "`. This is done to tell bash that your PS1 has invisible characters so it doesn't count them to "clear" the prompt in searches. But in `bashy` I'm not building the prompt with PS1, I'm just doing `echo`, and this doesn't work with this kind of escaping.

**Comment by pablopunk** [comment]
cc @egeriis

While I still don't know how to solve this, I created [this branch](https://github.com/pablopunk/bashy/tree/pure) that removes all colors/bold from the prompt, so the problem disappears.

**Comment by pablopunk** [comment]
@egeriis Okay I ended up merging the branch so it's solved in master!

**Comment by egeriis** [comment]
@pablopunk Thank you for the update. Sad that formatting had to be removed :/

**Comment by pablopunk** [comment]
@egeriis yeah, I might bring it back by allowing custom formats like vcprompt, so the user is the one declaring/escaping the formats.

For example `PS1='bashy -f "$bold %dir $normal %branch"'`

Let's see if I can do that!

**Comment by pablopunk** [comment]
@egeriis I finally solved the issue with [this answer](https://superuser.com/a/301355)

COLORS AND BOLD ARE BACK!
